name: Update Gradle Wrapper

on:
  push:
    branches:
      - main

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.20
